// Runs as the Vercel "build" step. Static hosting has no server-side
// runtime to read process.env at request time, so instead we bake the
// game server URL into env.js at build time, keeping the same
// NEXT_PUBLIC_GAME_SERVER_URL variable name called for in the spec.
const fs = require("fs");
const path = require("path");

const url = process.env.NEXT_PUBLIC_GAME_SERVER_URL || "http://localhost:3001";

const content = `// AUTO-GENERATED by scripts/generate-env.js at build time. Do not edit by hand.
window.__ENV__ = {
  GAME_SERVER_URL: ${JSON.stringify(url)},
};
`;

fs.writeFileSync(path.join(__dirname, "..", "env.js"), content);
console.log(`[generate-env] Wrote env.js with GAME_SERVER_URL=${url}`);
